core:
  enable-debug-messages: true
  match-offline-players: false
modules:
  AntiPortal: true
  CarbonCombat: true
  CarbonCrafting: true
  CarbonPerks: true
  CarbonTrivia: true
  CarbonVote: true
  CKWatcher: true
  CmdBlockTools: true
  EssentialsAssist: true
  Fireworks: false
  GoldenSmite: true
  Misc: true
  NetherSpawners: true
  SkullShop: true
AntiPortal:
  worlds:
  - world_the_end
  drop-egg: true
  generate-egg: false
  platform-mat: GLOWSTONE
  protect-egg: true
  egg-protect-seconds: 30
CarbonCombat:
  pvp-enabled:
  - world
  - world_nether
  player-toggle-enabled:
  - world
  prevent-block-shooters:
  - world
  - world_the_end
  disable-cooldown-seconds: 20
CarbonCrafting:
  shaped-recipes:
    SADDLE:
      recipe:
      - ''
      - LEATHER,,LEATHER
      - IRON_INGOT,LEATHER,IRON_INGOT
    NAME_TAG:
      amount: 2
      recipe:
      - PAPER,PAPER,
      - PAPER,SLIME_BALL,
      - ',,STRING'
    DIAMOND_BARDING:
      recipe:
      - ',DIAMOND'
      - DIAMOND,LEATHER,DIAMOND
      - LEATHER,LEATHER,LEATHER
    GOLD_BARDING:
      recipe:
      - ',GOLD_INGOT,'
      - GOLD_INGOT,LEATHER,GOLD_INGOT
      - LEATHER,LEATHER,LEATHER
    IRON_BARDING:
      recipe:
      - ',IRON_INGOT,'
      - IRON_INGOT,LEATHER,IRON_INGOT
      - LEATHER,LEATHER,LEATHER
  shapeless-recipes:
    LEATHER:
      recipe:
      - 2 ROTTEN_FLESH
      - 1 COAL 1
    COAL:
      durability: 1
      recipe:
      - 2 COAL
  furnace-recipes:
    LEATHER:
      source: ROTTEN_FLESH
CarbonNews:
  GeneralOptions:
    welcomeMessage:
      enabled: true
      delaySeconds: 2
      requirePermission: false
      messageLines:
      - '&3Welcome to {TTP~&aVisit our website @ team-carbon.org|TXT~&aTeam-Carbon}&3!
        Know the {CMD~/rules|TTP~Click to view the rules|TXT~&brules}&3 and
        enjoy your stay!'
    newGroupDefaults:
      delaySeconds: 60
      randomOrder: false
      requirePermission: false
      sendToConsole: true
      sendToPlayers: true
      colorizeConsoleMessages: true
      prefix: '&b&l[!] &3'
      postfix: ''
  MessageGroups:
    tutorial:
      groupEnabled: false
      delaySeconds: 60
      randomOrder: true
      requirePermission: false
      sendToConsole: true
      sendToPlayers: true
      colorizeConsoleMessages: true
      prefix: '{TTP~Tutorial Group!|TXT~&b&l[!]} &3'
      postfix: ''
      messages:
      - 'Formatting! {TTP~&bRuns /rules|CMD~/rules|TXT~&a&l&m&n&oCheck it!}'
      - 'Tags are delimited by a {TTP~&bA.K.A. a vertical bar, usually Shift + backslash(\)|TXT~&apipe} ''|''!'
      - 'Supported format tags are &6TTP&f, &6LNK&f, &6CMD&f, and &6TXT&f.'
      - 'Tags are wrapped in curly braces (the &6{ &fand &6} &fcharacters)'
      - 'Use ampersand (&6&&f) codes for colors and styles - like &a&l&m&n&othis!'
      - 'If using formats, you must include TXT and at least one other tag or it will be ignored!'
      - 'You can also use formats in the prefix and postfix!'
      - 'Tag headers must be uppercase and followed by a {TTP~&bUsually Shift + tick(`)|TEXT~&atilde} ''~''!'
      - 'You may mix ampersand color codes into formatting tags!'
      - 'Links will have an ''http://'' added before it if it doesn''t already have one or an ''https://'''
CarbonPerks:
  max-trails: 3
  firework-bow-damage-percent:
    mobs: 120.0
    players: 100.0
    disabled-worlds:
    - pvp_world
  fireworks-snowball-damage:
    mobs: 4.0
    players: 0.0
    disabled-worlds:
    - pvp_world
CarbonVote:
  vote-timeout-seconds: 30
  broadcast-votes: true
  majority-percent:
    weather: 66
    time: 66
    trivia: 66
    ban: 80
    kick: 75
    mute: 75
  nonvote-weight-percent:
    weather: -30
    time: -30
    trivia: -30
    ban: -100
    kick: -100
    mute: -100
  ban-time-seconds: 600
  mute-time-seconds: 300
  enabled-vote-types:
    weather: true
    time: true
    trivia: true
    ban: false
    kick: false
    mute: false
  vote-prices:
    weather: 10
    time: 30
    trivia: 50
    ban: 0
    kick: 0
    mute: 0
  min-players:
    weather: 1
    time: 1
    trivia: 6
    ban: 5
    kick: 5
    mute: 5
  vote-interval-seconds:
    weather: 600
    time: 600
    trivia: 900
    ban: 300
    kick: 120
    mute: 300
CKWatcher:
  match-aliases: true
  blacklist:
  - ej
  - j
  - list
  - msg
  - r
  - thru
  - goldensmite
  - mail
  - login
  - register
  - changepw
  exempt: []
CmdBlockTools:
  item-limit: 50
  spawn-limit: 50
  kill-radius-limit: 1000
  clear-radius-limit: 1000
  log-messages:
    spawn: true
    kill: true
    clear: true
    item: true
EssentialsAssist:
  message-on-auto-anti-interact: false
  vanish-toggles:
    prevent-item-pickup: true
    prevent-pressure: true
    prevent-mob-targeting: true
    prevent-damage: true
Fireworks:
  per-player-presets: 10
  extra-arrow-player-damage: 0.0
  extra-arrow-mob-damage: 0.0
  extra-snowball-player-damage: 0.0
  extra-snowball-mob-damage: 0.0
  presets: {}
GoldenSmite:
  range: 100
  radius: 8
  removeMobDrops: true
  removePlayerDrops: false
  removeExp: true
  explosionEffect: false
  lightningEffect: false
  fireworkEffect: true
Misc:
  slap-damage: 0.0
  slap-tool: BLAZE_ROD
  knockback: true
  entity-group-count: true
  entity-type-count: false
  entity-total-count: true
  online-time:
    show-years: true
    show-months: true
    show-days: true
    show-hours: true
    show-minutes: true
    show-seconds: false
NetherSpawners:
  enabled: true
  enabled-worlds:
  - world_nether
  per-chunk-chance-percent: 10
SkullShop:
  buy-price: 2000
  update-price: 500
