name: CarbonKit
version: 0.8
description: Plugin Kit Designed for Minecraft Team-Carbon
author: OffLuffy
depend: [CarbonLib, Vault]
soft-depend: [Essentials, GriefPrevention, WorldEdit]
main: net.teamcarbon.carbonkit.CarbonKit

commands:
  carbonkit:
    description: Base CarbonKit command, info and help
    usage: /ckit
    aliases: [ck, ckit]
  carbonkitreload:
    description: Reloads all modules and config files
    usage: /ckreload
    aliases: [ckreload, ckr, carbonkitr]
  carbonkittoggle:
    description: Lists modules or toggle a module on or off
    usage: /ckt [module]
    aliases: [cktoggle, ckt, carbonkitt]
  carbonkithelp:
    description: Overall CarbonKit help command
    usage: /ckh
    aliases: [ckh, ckh, carbonkith]
  carbonvote:
    description: CarbonKit Vote command
    usage: /cvote [ban|kick|mute|weather|time] <player>
    aliases: [cvote, cv, vote]
  carbontrivia:
    description: CarbonKit Trivia command
    usage: /trivia start
    aliases: [ctrivia, trivia, cktrivia, ctr]
  carbonkitwatcher:
    description: Toggle command watcher
    usage: /ckw
    aliases: [ckwatcher, ckw, cw]
  commandblockclear:
    description: Command block executed command to clear entities
    usage: /cbc [type] <radius>
    aliases: [cmdblockclear, cblockclear, cbclear, cbc]
  commandblockitem:
    description: Command block executed command to spawn items
    usage: /cbi [item] <amount>
    aliases: [cmdblockitem, cblockitem, cbitem, cbi]
  commandblockkill:
    description: Command block executed command to kill mobs
    usage: /cbk [mobs] <radius>
    aliases: [cmdblockkill, cblockkill, cbkill, cbk]
  commandblockspawn:
    description: Command block executed command to spawn mobs
    usage: /cbs [mobtype] <amount>
    aliases: [cmdblockspawn, cblockspawn, cbspawn, cbs]
  entitycount:
    description: Command to count the number of entities in a WE selection, radius, or the world
    usage: /ecount <radius>
    aliases: [entcount, ecount]
  fakejoin:
    description: Broadcasts a fake join message for you or a specified user
    usage: /fakejoin <user>
    aliases: [fjoin, fakej, falsejoin, falsej]
  fakequit:
    description: Broadcasts a fake quit message for you or a specified user
    usage: /fakequit <user>
    aliases: [fquit, fakeq, falsequit, falseq]
  firework:
    description: CarbonKit Fireworks command
    usage: /firework [help|list|preset|launch|spawn|arrow|snowball]
    aliases: [fw, ckfw, ckfirework]
  freeze:
    description: Freezes the specified user until restart or release
    usage: /freeze [user]
  gamemode:
    description: Gamemode switching command and per-mode permissions
    usage: /gamemode [mode] <user>
    aliases: [gm, mode, gmode]
  goldensmite:
    description: GoldenSmite an area, toggle affected entities, or toggle gsmite arrows
    usage: /gs <here|hmob|pmob|nmob|tame|player|drop|arrow>
    aliases: [gsmite, gs]
  customhelp:
    description: Custom help command to override Essential's or vanilla provided help command
    usage: /help [category]
  onlinetime:
    descriptoin: Allows viewing how long players have played on the server
    usage: /onlinetime <user>
    aliases: [ot, ontime]
  ride:
    description: Ride an entity you're looking at or the specified player
    usage: /ride <player>
  head:
    description: Buy or spawn a player head
    usage: /head [player]
    aliases: [skull, headshop, skullshop]
  updatehead:
    description: Allows you to update whose skin is on a head
    usage: /updatehead [player]
    aliases: [updateskull, uhead, uskull]
  dupehead:
    description: Buy or spawn a saved skull
    usage: /gskull
    aliases: [getskull,gskull,gethead,ghead,dupeskull,dskull,dupehead,dhead]
  slap:
    description: Slap a player
    usage: /slap [player]
  toggleinteract:
    description: Toggle interacting with pressure plates, tripwire, mobs, and drops when vanished
    usage: /ti
    aliases: [tinteract, tint, ti]
  trail:
    description: Sets a particle trail for yourself
    usage: /trail
    aliases: [trails, ctrail, ctrails]
  disabledcmd:
    description: Command to register disabled module commands to
permissions:
  carbonkit.reload:
    description: Access to reload CarbonKit
    default: op
  carbonkit.list:
    description: Access to list modules and see if they're enabled
    default: op
  carbonkit.toggle:
    description: Access to toggle individual modules
    default: op
  carbonkit.help:
    description: Access to CarbonKit help
    default: op
  carbonkit.cmdblocktools.help.item:
    description: Access to view help about the cbi command
    default: op
  carbonkit.cmdblocktools.help.spawn:
    description: Access to view help about the cbs command
    default: op
  carbonkit.cmdblocktools.help.clear:
    description: Access to view help about the cbc command
    default: op
  carbonkit.cmdblocktools.help.kill:
    description: Access to view help about the cbk command
    default: op
  carbonkit.ckwatcher.watchplayers:
    description: Access to watch player commands
    default: op
  carbonkit.ckwatcher.watchconsole:
    description: Access to watch server commands
    default: op
  carbonkit.ckwatcher.toggle:
    description: Access to toggle your watching state
    default: op
  carbonkit.ckwatcher.toggle.others:
    description: Access to toggle other users' watching state
    default: op
  carbonkit.essassist.toggle-interact:
    description: Access to toggle interacting
    default: op
  carbonkit.essassist.toggle-interact.others:
    description: Access to toggle other players' interacting
    default: op
  carbonkit.skullshop.skull:
    description: Access to buy player heads
    default: op
  carbonkit.skullshop.skull.free:
    description: Access to spawn player heads for free
    default: op
  carbonkit.skullshop.getskull:
    description: Access to buy or spawn saved player heads
    default: op
  carbonkit.skullshop.check:
    description: Access to save player heads by right-clicking an existing one
    default: op
  carbonkit.gamemode.others.survival:
    description: Set other users' mode to survival
    default: op
  carbonkit.gamemode.others.creative:
    description: Set other users' mode to creative
    default: op
  carbonkit.gamemode.others.adventure:
    description: Set other users' mode to adventure
    default: op
  carbonkit.gamemode.others.spectator:
    description: Set other users' mode to spectator
    default: op
  carbonkit.gamemode.self.survival:
    description: Set other users' mode to survival
    default: op
  carbonkit.gamemode.self.creative:
    description: Set other users' mode to creative
    default: op
  carbonkit.gamemode.self.adventure:
    description: Set other users' mode to adventure
    default: op
  carbonkit.gamemode.self.spectator:
    description: Set other users' mode to spectator
    default: op
  carbonkit.gamemode.others.*:
    description: Set other users' mode to any mode
    default: op
    children:
      carbonkit.gamemode.others.survival: true
      carbonkit.gamemode.others.creative: true
      carbonkit.gamemode.others.adventure: true
      carbonkit.gamemode.others.spectator: true
  carbonkit.gamemode.self.*:
    description: Set other users' mode to any mode
    default: op
    children:
      carbonkit.gamemode.self.survival: true
      carbonkit.gamemode.self.creative: true
      carbonkit.gamemode.self.adventure: true
      carbonkit.gamemode.self.spectator: true
  carbonkit.goldensmite.toggle.hostile:
    description: Access to toggle gsmite for hostile mobs
    default: op
  carbonkit.goldensmite.toggle.neutral:
    description: Access to toggle gsmite for neutral mobs
    default: op
  carbonkit.goldensmite.toggle.passive:
    description: Access to toggle gsmite for passive mobs
    default: op
  carbonkit.goldensmite.toggle.player:
    description: Access to toggle gsmite for players
    default: op
  carbonkit.goldensmite.toggle.tamed:
    description: Access to toggle gsmite for tamed mobs
    default: op
  carbonkit.goldensmite.toggle.drop:
    description: Access to toggle gsmite for ground items
    default: op
  carbonkit.goldensmite.here:
    description: Access to smite at your current location
    default: op
  carbonkit.goldensmite.immune.cmd:
    description: Immuntiy to cmd GSmites
    default: op
  carbonkit.goldensmite.immune.axe:
    description: Immuntiy to axe GSmites
    default: op
  carbonkit.goldensmite.immune.projectile:
    description: Immuntiy to projectile (arrow/snowball) GSmites
    default: op
  carbonkit.goldensmite.use.cmd:
    description: Access to use the GSmite command
    default: op
  carbonkit.goldensmite.use.axe:
    description: Access to use the GSmite axe
    default: op
  carbonkit.goldensmite.use.arrows:
    description: Access to use the GSmite arrows
    default: op
  carbonkit.goldensmite.use.snowballs:
    description: Access to use the GSmite snowballs
    default: op
  carbonkit.misc.artcycle:
    description: Access to right-click to cycle through painting art
    default: op
  carbonkit.misc.silentjoin:
    description: Join silently
    default: op
  carbonkit.misc.silentquit:
    description: Quit silently
    default: op
  carbonkit.misc.silentjoin.notify:
    description: Be notified when a player joins silently
    default: op
  carbonkit.misc.silentquit.notify:
    description: Be notified when a player quits silently
    default: op
  carbonkit.misc.freeze:
    description: Access to freeze players
    default: op
  carbonkit.misc.freeze.immune:
    description: Immuntiy to the freeze command
    default: op
  carbonkit.misc.fakequit:
    description: Access to fake-quit yourself
    default: op
  carbonkit.misc.fakequit.others:
    description: Access to fake-quit others
    default: op
  carbonkit.misc.quitmsg.extended:
    description: Access to view extended quit messages
    default: op
  carbonkit.misc.fakejoin:
    description: Access to fake-join yourself
    default: op
  carbonkit.misc.fakejoin.others:
    description: Access to fake-join others
    default: op
  carbonkit.misc.auto-anti-interact:
    description: Access to auto-anti-interact when vanished
    default: op
  carbonkit.misc.joinmsg.extended:
    description: Access to view extended join messages
    default: op
  carbonkit.misc.ride:
    description: Access to ride mobs
    default: op
  carbonkit.misc.ride.players:
    description: Access to ride players
    default: op
  carbonkit.misc.slap:
    description: Access to slap players
    default: op
  carbonkit.misc.onlinetime.self:
    description: View your own online time
    default: op
  carbonkit.misc.onlinetime.others:
    description: View other players' online time
    default: op
  carbonkit.carbonvote.receive-messages:
    description: Access to receive messages pertaining to voting
    default: true
  carbonkit.carbontrivia.answer:
    description: Access to answer trivia questions
    default: true
  carbonkit.carbontrivia.cheatnotify:
    description: Access to notifications of potential cheaters
    default: op
  carbonkit.carbontrivia.start:
    description: Access to start a trivia event
    default: op
  carbonkit.carbontrivia.end:
    description: Access to end a trivia event early
    default: op
  carbonkit.carbontrivia.cancel:
    description: Access to cancel a trivia event without distributing rewards
    default: op
  carbonkit.carbontrivia.help:
    description: Access to CarbonTrivia help
    default: op
  carbonkit.fireworks.help:
    description: Access to fireworks help
    default: op
  carbonkit.fireworks.presets.list.others:
    description: Access to list presets created by other users
    default: op
  carbonkit.fireworks.bypasslimit:
    description: Access to bypass the limit of number of presets you can create
    default: op
  carbonkit.fireworks.presets.delete:
    description: Access to delete presets you create
    default: op
  carbonkit.fireworks.presets.delete.others:
    description: Access to delete other users' presets
    default: op
  carbonkit.fireworks.presets.combine:
    description: Access to combine effects into one of your existing presets
    default: op
  carbonkit.fireworks.presets.combine.others:
    description: Access to combine effects into another user's existing presets
    default: op
  carbonkit.fireworks.presets.create:
    description: Access to to create presets
    default: op
  carbonkit.fireworks.presets.modify:
    description: Access to modify your existing preests
    default: op
  carbonkit.fireworks.presets.modify.others:
    description: Access to modify other users' existing presets
    default: op
  carbonkit.fireworks.preset.help:
    description: Access to preset-specified help
    default: op
  carbonkit.fireworks.launch.preset:
    description: Access to launch a firework with the specified preset effects
    default: op
  carbonkit.fireworks.launch.params:
    description: Access to launch a firework with specified parameters
    default: op
  carbonkit.fireworks.launch.hand:
    description: Access to launch the in-hand firework's effects
    default: op
  carbonkit.fireworks.launch.help:
    description: Access to launch-specified help
    default: op
  carbonkit.fireworks.effect.preset:
    description: Access to reproduce a firework effect with the specified preset effects
    default: op
  carbonkit.fireworks.effect.params:
    description: Access to reproduce a firework effect with the specified parameters
    default: op
  carbonkit.fireworks.effect.hand:
    description: Access to reproduce a firework effect with the in-hand firework's effects
    default: op
  carbonkit.fireworks.effect.help:
    description: Access to effect-specific help
    default: op
  carbonkit.fireworks.arrow.toggle:
    description: Access to toggle firework arrows
    default: op
  carbonkit.fireworks.arrow.preset:
    description: Access to set the firework arrow effects to a preset
    default: op
  carbonkit.fireworks.arrow.hand:
    description: Access to set the firework arrow effects to the in-hand firework's effects
    default: op
  carbonkit.fireworks.snowball.toggle:
    description: Access to toggle firework snowballs
    default: op
  carbonkit.fireworks.snowball.preset:
    description: Access to set the firework snowball effects to a preset
    default: op
  carbonkit.fireworks.snowball.hand:
    description: Access to set the firework snowball effects to the in-hand firework's effects
    default: op
  carbonkit.fireworks.spawn:
    description: Access to spawn fireworks
    default: op
  carbonkit.fireworks.use.arrows:
    description: Access to use firework arrows
    default: op
  carbonkit.fireworks.use.snowballs:
    description: Access to use firework snowballs
    default: op
  carbonkit.vote.time.start:
    description: Access to start a time vote
    default: op
  carbonkit.vote.weather.start:
    description: Access to start a weather vote
    default: op
  carbonkit.vote.ban.start:
    description: Access to start a ban vote
    default: op
  carbonkit.vote.kick.start:
    description: Access to start a kick vote
    default: op
  carbonkit.vote.mute.start:
    description: Access to start a mute vote
    default: op
  carbonkit.vote.jail.start:
    description: Access to start a jail vote
    default: op
  carbonkit.vote.trivia.start:
    description: Access to start a trivia vote
    default: op
  carbonkit.vote.time.vote:
    description: Access to vote on a time vote
    default: true
  carbonkit.vote.weather.vote:
    description: Access to vote on a weather vote
    default: true
  carbonkit.vote.ban.vote:
    description: Access to vote on a ban vote
    default: true
  carbonkit.vote.kick.vote:
    description: Access to vote on a kick vote
    default: true
  carbonkit.vote.mute.vote:
    description: Access to vote on a mute vote
    default: true
  carbonkit.vote.jail.vote:
    description: Access to vote on a jail vote
    default: true
  carbonkit.vote.trivia.vote:
    description: Access to vote on a trivia vote
    default: true
  carbonkit.vote.time.bypasscooldown:
    description: Access to bypass the weather vote cooldown
    default: op
  carbonkit.vote.weather.bypasscooldown:
    description: Access to bypass the weather vote cooldown
    default: op
  carbonkit.vote.ban.bypasscooldown:
    description: Access to bypass the weather vote cooldown
    default: op
  carbonkit.vote.kick.bypasscooldown:
    description: Access to bypass the weather vote cooldown
    default: op
  carbonkit.vote.mute.bypasscooldown:
    description: Access to bypass the weather vote cooldown
    default: op
  carbonkit.vote.jail.bypasscooldown:
    description: Access to bypass the weather vote cooldown
    default: op
  carbonkit.vote.trivia.bypasscooldown:
    description: Access to bypass the weather vote cooldown
    default: op
  carbonkit.perks.trails.random:
    description: Set a random particle trail
    default: op
  carbonkit.perks.trails.set:
    description: Set a specified particle trail
    default: op
  carbonkit.perks.trails.set.*:
    description: Set any particle trail
    default: op
    children:
      carbonkit.perks.trails.set.smoke: true
      carbonkit.perks.trails.set.ender_signal: true
      carbonkit.perks.trails.set.fireworks_spark: true
      carbonkit.perks.trails.set.crit: true
      carbonkit.perks.trails.set.magic_crit: true
      carbonkit.perks.trails.set.potion_swirl: true
      carbonkit.perks.trails.set.spell: true
      carbonkit.perks.trails.set.instant_spell: true
      carbonkit.perks.trails.set.witch_magic: true
      carbonkit.perks.trails.set.note: true
      carbonkit.perks.trails.set.portal: true
      carbonkit.perks.trails.set.flying_glyph: true
      carbonkit.perks.trails.set.flame: true
      carbonkit.perks.trails.set.lava_pop: true
      carbonkit.perks.trails.set.footstep: true
      carbonkit.perks.trails.set.splash: true
      carbonkit.perks.trails.set.small_smoke: true
      carbonkit.perks.trails.set.coloured_dust: true
      carbonkit.perks.trails.set.waterdrip: true
      carbonkit.perks.trails.set.slime: true
      carbonkit.perks.trails.set.heart: true
      carbonkit.perks.trails.set.villager_thundercloud: true
      carbonkit.perks.trails.set.happy_villager: true
      carbonkit.perks.trails.set.tile_break: true
  carbonkit.perks.trails.add:
    description: Add additional particles trails on top of current ones
    default: op
  carbonkit.perks.trails.remove:
    description: Remove particle trails from currently set trails
    default: op
  carbonkit.perks.trails.clear:
    description: Remove all particle trails and disable them
    default: op
  carbonkit.perks.trails.toggle:
    description: Toggle the active state of a particle trail
    default: op
  carbonkit.perks.trails.multiple:
    description: Allows using multiple trails (limit of trails in config)
    default: op