name: CarbonKit
version: 0.8
description: Plugin Kit Designed for Minecraft Team-Carbon
author: OffLuffy
depend: [CarbonLib, Vault]
soft-depend: [Essentials, GriefPrevention, WorldEdit]
main: net.teamcarbon.carbonkit.CarbonKit

commands:
  carbonkit:
    description: Base CarbonKit command, info and help
    usage: /ckit
    aliases: [ck, ckit]
  carbonreload:
    description: Reloads all modules and config files
    usage: /ckreload
    aliases: [carbonkitreload, ckreload, creload, ckr]
  carbontoggle:
    description: Lists modules or toggle a module on or off
    usage: /ckt [module]
    aliases: [cktoggle, ckt, carbonkitt]
  carbonvote:
    description: CarbonKit Vote command
    usage: /cvote [ban|kick|mute|weather|time] <player>
    aliases: [cvote, cv, vote]
  carbontrivia:
    description: CarbonKit Trivia command
    usage: /trivia start
    aliases: [ctrivia, trivia, cktrivia, ctr]
  carbonwatcher:
    description: Toggle command watcher
    usage: /cw
    aliases: [ckwatcher, cwatcher, ckw, cw]
  entitycount:
    description: Command to count the number of entities in a WE selection, radius, or the world
    usage: /ecount <radius>
    aliases: [entcount, ecount, ckentitycount, ckentcount, ckecount, ckec]
  fakejoin:
    description: Broadcasts a fake join message for you or a specified user
    usage: /fakejoin <user>
    aliases: [fjoin, fakej, falsejoin, falsej, ckfakejoin]
  fakequit:
    description: Broadcasts a fake quit message for you or a specified user
    usage: /fakequit <user>
    aliases: [fquit, fakeq, falsequit, falseq, ckfakequit]
  firework:
    description: CarbonKit Fireworks command
    usage: /firework [help|list|preset|launch|spawn|arrow|snowball]
    aliases: [fw, ckfw, ckfirework]
  freeze:
    description: Freezes the specified user until restart or release
    usage: /freeze [user]
    aliases: [ckfreeze]
  gamemode:
    description: Gamemode switching command and per-mode permissions
    usage: /gamemode [mode] <user>
    aliases: [gm, mode, gmode, ckgm, ckgamemode, ckmode, ckgmode]
  goldensmite:
    description: GoldenSmite an area, toggle affected entities, or toggle gsmite arrows
    usage: /gs <here|hmob|pmob|nmob|tame|player|drop|arrow>
    aliases: [gsmite, gs, ckgoldensmite, ckgsmite, ckgs]
  help:
    description: Custom help command to override Essential's or vanilla provided help command
    usage: /help [category]
    aliases: [carbonkithelp, carbonhelp, ckhelp, chelp]
  onlinetime:
    descriptoin: Allows viewing how long players have played on the server
    usage: /onlinetime <user>
    aliases: [ot, ontime, ckot, ckontime, ckonlinetime]
  ride:
    description: Ride an entity you're looking at or the specified player
    usage: /ride <player>
    aliases: [ckride]
  head:
    description: Buy or spawn a player head
    usage: /head [player]
    aliases: [skull, headshop, skullshop, ckskull, ckhead]
  updatehead:
    description: Allows you to update whose skin is on a head
    usage: /updatehead [player]
    aliases: [updateskull, uhead, uskull, ckuskull, ckuhead]
  dupehead:
    description: Buy or spawn a saved skull
    usage: /gskull
    aliases: [getskull, gskull, gethead, ghead, dupeskull, dskull, dupehead, dhead, ckdskull, ckdhead]
  slap:
    description: Slap a player
    usage: /slap [player]
    aliases: [ckslap]
  toggleinteract:
    description: Toggle interacting with pressure plates, tripwire, mobs, and drops when vanished
    usage: /ti
    aliases: [tinteract, tint, ti, cktinteract, cktint, ckti]
  trail:
    description: Sets a particle trail for yourself
    usage: /trail
    aliases: [trails, ctrail, ctrails, cktrails, cktrail]
  carbonnews:
    description: CarbonNews command
    usage: /carbonnews
    aliases: [cnews, cn, cknews]
  ticket:
    description: Creates a ticket for suggestions/reports/bugs, etc
    usage: /ticket [message]
    aliases: [report, ckticket, ckreport, cticket, creport, rpt, tk, ckrpt, cktk, crpt, ctk]
  dice:
    description: Roll a virtual dice for a random number
    usage: /dice [max] [min]
    aliases: [roll, ckdice, ckroll]
  animalinfo:
    description: View info about an animal
    usage: /animalinfo
    aliases: [ckanimalinfo, ckainfo, ckai, ai]
  warp:
    description: Teleports to pre-set locations
    usage: /warp [warp]
  vanish:
    description: Hides a player from others with permission to see vanished players
    usage: /vanish
    aliases: [v]
  carboncombat:
    description: Toggles PvP enabled
    usage: /carboncombat [on|off] [player]
    aliases: [pvp, combat]
  disabledcmd:
    description: Command to register disabled module commands to